// Authentication middleware

import jwt from "jsonwebtoken";

const auth = async (req, res, next) => {
  try {
    // Get the user token from the frontend.
    const token = req.headers.authorization.split(" ")[1];

    // If the length is less than 500, the token is a custom one
    // and not generated by google auth.
    const isCustomToken = token.length < 500;

    let decodedData;

    // If the token is a custom one () token, then
    // decode it by verifying with the secret string
    // that was used in making that token.
    if (token && isCustomToken) {
      decodedData = jwt.verify(token, "test");

      // Getting the user id from the token.
      req.userId = decodedData?.id;
    } else {
      decodedData = jwt.decode(token);
      req.userId = decodedData?.sub;
    }

    // After verifying user, proceed onto doing something else.
    next();
  } catch (error) {
    console.log(error);
  }
};

export default auth;
